<?php include("header.php");?>
<?php include("menu.php");?>
    <section class="content">
        <!-- <article class="item">
            <a href="https://patriciogonzalezvivo.github.io/weaver"><img class="roundPhotoTh" src="2025/weaver/thumb.gif" alt="Light Weaver: connecting people across time and space through common stars."/></a>
            <p>2025 <strong>Light Weaver</strong>: connecting people across time and space through common stars. </p>
        </article>     -->
    <!-- <article class="item">
            <a href="https://objkt.com/collection/KT1CkDFaHiH8UtZhyR2EvoqhihsntjSikvt9"><img class="roundPhotoTh" src="2021/arcana/thumb.gif" alt="Memory Studies"/></a>
            <p>2021 <strong>PixelFlair ARCANA</strong>: real-time NFT based on the 22 Arcana of PixelSpirit Tarot Deck.</p>
        </article> -->
        <article class="item">
            <!-- <a href="2021/memory/"><img class="roundPhotoTh" src="2021/memory/thumb.gif" alt="Memory Studies"/></a> -->
            <a href="https://patriciogonzalezvivo.github.io/MemoryStudy"><img class="roundPhotoTh" src="2021/memory/thumb.gif" alt="Memory Studies"/></a>
            <p>2021 <strong>Memory Studies</strong> </p>
        </article>
        <article class="item">
            <a href="2021/fen/"><img class="roundPhotoTh" src="2021/fen/thumb.gif" alt="Flight Studies"/></a>
            <p>2021 <strong>Flight Studies</strong>: part of The FEN, the first NFT collection on the Tezos market</p>
        </article>
        <article class="item">
            <a href="https://vimeo.com/332883913"><img class="roundPhotoTh" src="2019/hogar/thumb.gif" alt="HOGAR"/></a>
            <p>2019 <strong>Hogar</strong>: an oportunity to see a bigger picture</p>
        </article>
        <article class="item">
            <a href="https://patriciogonzalezvivo.github.io/Estrellas"><img class="roundPhotoTh" src="2018/estrellas/thumb.gif" alt="ESTRELLAS"/></a>
            <!-- <a href="https://vimeo.com/278951084"><img class="roundPhotoTh" src="2018/estrellas/thumb.gif" alt="ESTRELLAS"/></a> -->
            <!-- <a href="https://frm.fm/a/patricio_gonzalez_vivo/estrellas"><img class="roundPhotoTh" src="2018/estrellas/thumb.gif" alt="ESTRELLAS"/></a> -->
            <p>2018 <strong>Estrellas</strong>: a window to the starry sky.</p>
        </article>
        <article class="item">
            <a href="https://vimeo.com/278713624"><img class="roundPhotoTh" src="2018/orbitas/thumb.gif" alt="Orbitas"/></a>
            <!-- <a href="http://frm.fm/a/patricio_gonzalez_vivo/orbitas"><img class="roundPhotoTh" src="2018/orbitas/thumb.gif" alt="Orbitas"/></a> -->
            <p>2018 <strong>Órbitas</strong>: realtime simulation that explores the patterns generated by planets and satellites.</p>
        </article>
        <article class="item">
            <a href="http://pixelspiritdeck.com/"><img class="roundPhotoTh" src="2017/pixelspirit/thumb.gif" alt="PixelSpirit"/></a>
            <p>2017 <strong>PixelSpirit</strong>: one deck of cards for the modern GPU wizard of light</p>
        </article>
        <article class="item">
            <a href="https://patriciogonzalezvivo.github.io/Estrellas"><img class="roundPhotoTh" src="2017/luna/thumb.jpg" alt="LUNA"/></a>
            <!-- <a href="https://vimeo.com/278742301"><img class="roundPhotoTh" src="2017/luna/thumb.jpg" alt="LUNA"/></a> -->
            <!-- <a href="https://frm.fm/a/patricio_gonzalez_vivo/luna"><img class="roundPhotoTh" src="2017/luna/thumb.jpg" alt="LUNA"/></a> -->
            <p>2017 <strong>LUNA</strong>: quietly mirrors the moon’s phases and the passage of day and night</a></p>
        </article>
        <article class="item">
            <a href="http://themapisnot.com/issue-iv-patricio-gonzalez-vivo-jen-lowe"><img class="roundPhotoTh" src="2017/guayupia/thumb.jpg" alt="GUAYUPIA"/></a>
            <p>2017 <strong>GUAYUPIA</strong>: in the search of a land with no evil with <a href="http://jenlowe.net/" targer="_window">Jen Lowe</a></p>
        </article>
        <article class="item">
            <a href="https://vimeo.com/249558671"><img class="roundPhotoTh" src="2015/LineOfSight/thumb.gif" alt="LineOfSight"/></a>
            <!-- <a href="https://patriciogonzalezvivo.github.io/LineOfSight"><img class="roundPhotoTh" src="2015/LineOfSight/thumb.gif" alt="LineOfSight"/></a> -->
            <p>2015 <strong>LineOfSight</strong>: find and track satellites</p>
        </article>
        <article class="item">
            <a href="https://vimeo.com/141590783"><img class="roundPhotoTh" src="2015/RandomCity/thumb.gif" alt="RandomCity"/></a>
            <!-- <a href="https://patriciogonzalezvivo.github.io/RandomCity/"><img class="roundPhotoTh" src="2015/RandomCity/thumb.gif" alt="RandomCity"/></a> -->
            <p>2015 <strong>RandomCity</strong>: though the streams are chaotic, they coalesce into a digital harmony</p>
        </article>
        <article class="item">
            <a href="http://thebookofshaders.com/"><img class="roundPhotoTh" src="https://thebookofshaders.com/thumb.jpg" alt="TheBookOfShaders"/></a>
            <p>2015 <strong>The Book of Shaders</strong>: Who said #shaders are a dark art? </p>
        </article>
        <!-- <article class="item">
            <a href="2015/tangram-sandbox/"><img class="roundPhotoTh" src="2015/tangram-sandbox/thumb.png" alt="Tangram-Sandbox"/></a>
            <p>2015 <strong>Tangram Sandbox</strong>: series of experimental styles for maps based on GLSL shaders</p>
        </article> -->
        <!-- <article class="item">
            <a href="2014/lidar/"><img class="roundPhotoTh" src="2014/lidar/thumb.gif" alt="Lidar"/></a>
            <p>2014 <strong>crowdsourcing Point Clouds </strong>for 3D mapping.</p>
        </article> -->
        <article class="item">
            <a href="2014/skylines/"><img class="roundPhotoTh" src="2014/skylines/thumb.png" alt="SKYLINES"/></a>
            <p>2014 <strong>SKYLINES</strong>: three projects about awareness and tools for seeing</p>
        </article>
        <article class="item">
            <a href="2014/pointcloudcity/"><img class="roundPhotoTh" src="2014/pointcloudcity/thumb.gif" alt="PointCloudCity"/></a>
            <p>2014 <strong>Point Cloud City</strong>: private data landscapes of public places</p>
        </article>
        <article class="item">
            <a href="2013/clouds/"><img class="roundPhotoTh" src="2013/clouds/thumb.jpg" alt="clouds"/></a>
            <p>2013 <strong>CLOUDS Documentary</strong>: collaboration of poetic Visual Systems</p>
        </article>
		<!-- <article class="item">
            <a href="https://vimeo.com/54093238" target="_blank"><img class="roundPhotoTh" src="2012/codemology/thumb.jpg" alt="CodeMology"/></a>
			<p>2012 <strong>Codemology</strong>: explorations between code and alquemy</p>
        </article> -->

        <article class="item">
            <a href="https://github.com/patriciogonzalezvivo/flatland" target="_blank"><img class="roundPhotoTh" src="2012/flatland/thumb.jpg" alt="FlatLand"/></a>
            <p>2012 <strong>FlatLand</strong>: collaboration with <a href="http://thesystemis.com/" target="_blank">Zach Lieberman</a> for New Cinema Hackathon at EyeBeam </p>
        </article>
        <article class="item">
            <a href="2011/efectomariposa/"><img class="roundPhotoTh" src="2011/efectomariposa/thumb.jpg" alt="Efecto Mariposa"/></a>
            <p>2011 <strong>Efecto Mariposa</strong>: realtime ecosystem simulator</p>
        </article>
        <!-- <article class="item">
			<a href="https://vimeo.com/19198053" target="_blank"><img class="roundPhotoTh" src="2011/liquidkinect/thumb.jpg" alt="Liquid Kinect"/></a>
			<p>2011 <strong>Liquid Kinect</strong>: Kinect + Particle System + GLSL Shaders</p>
		</article> -->
        <article class="item">
            <a href="2010/communitas/"><img class="roundPhotoTh" src="2010/communitas/thumb.jpg" alt="Communitas"/></a>
            <p>2010 <strong>Communitas</strong>: collective drawing interactive installation</p>
        </article>
    </section>

<?php include("footer.php"); ?>
